title: Muhammad Zain Ul Abideen 
author: Muhammad Zain Ul Abideen (@xenbaloch)
email: xenbaloch@live.com 
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am glad to see you here. Please scrol down to know more about me.

# social links
twitter_username: zainbaloch14
github_username:  xenbaloch

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
